### ISSUE TITLE
Improve http body consumption

### ISSUE THREAD

**Issue by skonto** [sjwiesman/statefun-go#1]
Right now we use ReadAll https://github.com/sjwiesman/statefun-go/blob/6e127f97b3364df52a1c736ded15a80e91ae2b32/pkg/flink/statefun/stateful_functions.go#L76) which suffers from [memory issues ](https://www.openmymind.net/Go-Slices-And-The-Case-Of-The-Missing-Memory/)since each call creates a temporary buffer. This could happen when a big number of invocations is happening.
Maybe we should add benchmarks here for this and other paths. A `sync.Pool` might be a good option here but needs proper implementation as there are [issues](https://github.com/golang/go/issues/23199) if request size varies a lot.

**Comment by slinkydeveloper** [comment]
For a pool of byte buffers there is this library https://github.com/valyala/bytebufferpool which is very well tested and production ready (fasthttp uses it behind the hood for everything)

**Comment by skonto** [comment]
Another approach would be the [multi-size pool](https://github.com/golang/go/blob/7e394a2/src/net/http/h2_bundle.go#L998-L1043).

**Comment by sjwiesman** [comment]
The payload size is variable, because each request contains the information for a variable number of function invocations. Up to n where n is configured on the flink runtime side and not known by the sdk.

**Comment by skonto** [comment]
@sjwiesman You want to avoid gc issues that come with readAll especially if n is large.  Check my link above, you can easily target for the average case with a fixed size pool.

**Comment by sjwiesman** [comment]
fixed in master: 9dd293381789c7977492cfa77c20efc20f7a319b
