### ISSUE TITLE
Rename package 

### ISSUE THREAD

**Issue by sjwiesman** [sjwiesman/statefun-go#3]
The current package `statefun_go` is not idiomatic with its underscore. We should rename it to something else. 

I'm not sure if it is alright to have the package structure different from the file structure but the end goal is to donate this codebase to apache/flink-statefun which is a mono-repo containing multiple languages. This means will want some signifier that this package contains the go sdk specifically.

**Comment by marcellanz** [comment]
One probably would have a separate repository for the go implementation here in the flink project especially which will have a descriptive name state that this is the go sdk of statefun perhaps something like: `https://github.com/apache/flink-statefun-go` and then having descriptive packages. File directory structure also  follow the package structure. More about this can be found here:
https://golang.org/doc/effective_go.html#names
https://blog.golang.org/package-names

**Comment by sjwiesman** [comment]
Thanks for the resources!

fixed in bdd63ac6fd92654d1b84411e03dd15f8c32ad970
