### ISSUE TITLE
how can i run through the whole process

### ISSUE THREAD

**Issue by zhaijian** [sjwiesman/statefun-go#5]
i pull the code
go run main.go
when i use curl function, it doesn't work, 
curl localhost:8000/statefun -d '{"name":"aaa", "visits":1}'  -H 'Content-Type:application/octet-stream'
then report errors
failed to unmarshal ToFunction: proto: cannot parse invalid wire-format data

what's wrong with it, thanks

**Comment by sjwiesman** [comment]
The GoLang SDK has been donated to the Apache Flink - StateFun project. You can find the documentation there. https://nightlies.apache.org/flink/flink-statefun-docs-master/
